### ISSUE TITLE
`AttributeError: 'InferenceInfo' object has no attribute 'output_tokens'.` after #410

### ISSUE THREAD

**Issue by diamondburned** [kubernetes-sigs/inference-perf#453]
**What happened**:

All inference-perf requests fail with the following exception:

```
  File "/nix/store/3lll9y925zz9393sa59h653xik66srjb-python3-3.13.9/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/loadgen/load_generator.py", line 263, in run
    run(self.loop())
    ~~~^^^^^^^^^^^^^
  File "/nix/store/3lll9y925zz9393sa59h653xik66srjb-python3-3.13.9/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/nix/store/3lll9y925zz9393sa59h653xik66srjb-python3-3.13.9/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/loadgen/load_generator.py", line 247, in loop
    await gather(*tasks)
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/loadgen/load_generator.py", line 201, in schedule_client
    await self.client.process_request(request_data, stage_id, request_time, lora_adapter)
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/client/modelserver/openai_client.py", line 120, in process_request
    await session.process_request(data, stage_id, scheduled_time, lora_adapter)
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/client/modelserver/openai_client.py", line 387, in process_request
    self._record_otel_metrics(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        span=span,
        ^^^^^^^^^^
    ...<6 lines>...
        end_time=end_time,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/inference_perf/client/modelserver/openai_client.py", line 190, in _record_otel_metrics
    "completion_tokens": response_info.output_tokens,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/diamondburned/Projects/kubernetes-sigs/inference-perf/.venv/lib/python3.13/site-packages/pydantic/main.py", line 1026, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'InferenceInfo' object has no attribute 'output_tokens'. Did you mean: 'input_tokens'?
```

**What you expected to happen**:

Requests do not fail.

**How to reproduce it (as minimally and precisely as possible)**:

Run with the following `config.yaml`:

```yaml
load:
  type: constant
  interval: 15
  stages:
    - {rate: 1, duration: 10}
  worker_max_concurrency: 100
api:
  type: completion
  streaming: true
server:
  type: vllm
  model_name: Qwen/Qwen3.5-27B
  base_url: http://0.0.0.0:8000
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: Qwen/Qwen3.5-27B
data:
  type: shared_prefix
  shared_prefix:
    num_groups: 256
    num_prompts_per_group: 16
    system_prompt_len: 512
    question_len: 256
    output_len: 256
report:
  request_lifecycle:
    summary: true
```

Either vLLM production or llm-d-inference-sim will work for replicating this.

**Anything else we need to know?**:

**Environment**:
- inference-perf version: commit 3b882ba21e9d81f1478eb331c0a266531d216a5e
- config.yml (entire one printed by the benchmark run): (shown above)
- cloud provider or hardware configuration: running bare on Cloudtop via the Nix shell

This seems to be a regression introduced by #410. With `git checkout HEAD^`, requests start passing again.

**Comment by diamondburned** [comment]
Fixed in https://github.com/kubernetes-sigs/inference-perf/pull/454.
